//@ compile-flags: -Ztypeck
contract C {
  function f() public {
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
    continue; //~ ERROR: `continue` outside of a loop
  }
}
