//@ compile-flags: -Ztypeck
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found
import "a.sol"; //~ ERROR: file a.sol not found

contract C {
  function f() public {
  }
}
