//@ compile-flags: -Ztypeck
pragma abicoder v1;
struct Item {
    uint x;
    uint y;
}

contract D {
    Item[][][] public items;

    function test() public view returns (uint) {
        // The autogenerated getters to not use ABI encoder.
        Item memory item = this.items(1, 2, 3); //~ ERROR: mismatched number of components
//~^ ERROR: mismatched types
        return item.x + item.y;
    }
}
